# config file for transfer learning example on MNIST

training:
  batch_size: 128
  n_epochs: 1000
  n_iters: 5001
  ngpu: 1
  snapshot_freq: 500
  algo: 'dsm'
  anneal_power: 2.0

data:
  dataset: "smallnorb"
  image_size: 64
  channels: 1
  logit_transform: false
  random_flip: true
  random_state: 0
  split_size: .15

model:
  sigma_begin: 1
  sigma_end: 0.01
  num_classes: 10
  batch_norm: true
  ngf: 64
  final_layer: true
  feature_size: 90
  augment: true
  positive: false
  architecture: 'simple'

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  amsgrad: false

n_labels: 8
